# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvabe\Documents\QuadballScoreboard\Graphical QT5\timekeeper_connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Timekeeper(object):
    def setupUi(self, Timekeeper):
        Timekeeper.setObjectName("Timekeeper")
        Timekeeper.resize(1272, 471)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Timekeeper)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Timekeeper)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Timekeeper)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(Timekeeper)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connectButton = QtWidgets.QPushButton(Timekeeper)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_3.addWidget(self.connectButton)
        self.closeButton = QtWidgets.QPushButton(Timekeeper)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Timekeeper)
        self.connectButton.clicked.connect(Timekeeper.connect) # type: ignore
        self.closeButton.clicked.connect(Timekeeper.close) # type: ignore
        self.pushButton.clicked.connect(Timekeeper.fetch_games) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Timekeeper)

    def retranslateUi(self, Timekeeper):
        _translate = QtCore.QCoreApplication.translate
        Timekeeper.setWindowTitle(_translate("Timekeeper", "Timekeeper"))
        self.label.setText(_translate("Timekeeper", "Enter GameID"))
        self.pushButton.setText(_translate("Timekeeper", "Fetch Games"))
        self.connectButton.setText(_translate("Timekeeper", "Connect"))
        self.closeButton.setText(_translate("Timekeeper", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Timekeeper = QtWidgets.QDialog()
    ui = Ui_Timekeeper()
    ui.setupUi(Timekeeper)
    Timekeeper.show()
    sys.exit(app.exec_())
